# Generated by Django 4.2.26 on 2025-11-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20),
        ),
        migrations.AddField(
            model_name='auction',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='minimum_bid_increment',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
