# Generated by Django 4.2.26 on 2025-11-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_condition_auction_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='shipping_method',
            field=models.CharField(choices=[('pickup', 'Pickup Only'), ('shipping', 'Shipping Available')], default='pickup', max_length=20),
        ),
    ]
