# Generated by Django 4.2.26 on 2025-11-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_shipping_cost_auction_shipping_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='image_url',
        ),
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='auction_images/'),
        ),
    ]
